### ISSUE TITLE
Encryption RSA key is "compact"

### ISSUE THREAD

**Issue by kubasiemion** [hyperledger/avalon#101]
The encryption RSA key is generated and marshalled to a "pem" format at the TCS start:
`JSON serialized worker info is {"workerType": [...], "encryptionKey": "-----BEGIN RS
A PUBLIC KEY-----\nMIIBCgKCAQEAsq7Bbdkb/O7Z05zAqONVteRZC/G1WgwiTpNuscUjnlLs9yqvux3x\n6GJESSeQ7kEtz/lPcdqkWHXPAjpFh1HPqoqklkQr7tjCzwYgC9hA8L6byJPaErdC\nDJXmJkHwiBMDuRPTMGOBQuBIp74kf6w/1EhfYjgpgyhpZVHCk8aPfaydG8PgNwGu\niJCLvLBEXRfNSmDBTGgFSdMMp+owGF0xDbd8bgG3Mk3tEpbQMaDXjsJkQ1mn3P0s\nw1Znx8S9u9r0nSX6xFl2mKqAODEBdAf14pjmbOe9U0DEWHE/ZjaeNsgHXfVB/st2\nXeTYgiW2iheqnZ0SYmqGbqasB++3Sq0IiwIDAQAB\n-----END RSA PUBLIC KEY-----\n", "encryptionKeySignature": ""}}, "status": 1}` 
This is the format in which it is being subsequently propagated.
Alas, one cannot easily parse this key (try to paste into a *.pem file and use as input for openssl). That is because only carries the internal part of the key (270 bytes). It misses the RSA OID, which, together with ASN1/DER formatting would make it 294 bytes long. 
Now I may not know what exactly I am writting about, but it took me a hack to get the interoperability with other std crypto libraries (go/crypto, go/spacemonkeys, ...). A hack that is not available on StackExchange! So how about our young audience?

**Comment by danintel** [comment]
The key should not be hard-coded to a specific algorithm.  Including the RSA OID will allow changes in the future and make it more flexible.

**Comment by kubasiemion** [comment]
Well, it is more of a hunch how it should be written rather than a "suggested fix" :-)
But yes, to my uninitiated eye that is the way to go. Very good point on the flexibility of the code -  honestly, have not even thought about it... 
I can work out a full fix, but probably only after Devcon. Unless somebody takes care of that earlier.

> The root reason (I think) is that in
> `trusted-compute-framework/tc/sgx/common/crypto/pkenc_public_key.cpp`
> the methods
> `PEM_read_bio_RSAPublicKey(...)`
> and
> `PEM_write_bio_RSAPublicKey(...)`
> are used directly, without passing `trough PEM_read_bio_PUBKEY(...)`, etc.

**Comment by kubasiemion** [comment]
A lazy fix is to prepend the RSA2048 key as it is currently generated with the following bytes:
30820122300d06092a864886f70d01010105000382010f00
(This of course has to be done *before* the base64 and pem encoding.) 
This in ASN1 book would read:
   0:d=0  hl=4 l= 290 cons: SEQUENCE
   4:d=1  hl=2 l=  13 cons: SEQUENCE
   6:d=2  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  17:d=2  hl=2 l=   0 prim: NULL
  [...] (followed by the original public key as two bigints). 

At least some libraries have difficulties parsing the pubkey bytes without this preamble.

**Comment by danintel** [comment]
@kubasiemion,
I took your ideas and used them in PR #502 .
The latter PR accepts both format strings for deserialization (BEGIN RSA PUBLIC KEY and BEGIN PUBLIC KEY),
but only writes BEGIN PUBLIC KEY pem strings.
I also add some tests to avoid future regression.

**Comment by danintel** [comment]
Fixed with the integration of PR #502
