### ISSUE TITLE
The use of '0x' prefix for hex values is inconsistent

### ISSUE THREAD

**Issue by kubasiemion** [hyperledger/avalon#121]
It is about the JSON formats.
Sample values:
"workOrderId": "0xb152345d18e8a0f6"
 "requesterId": "0x3456"

"workloadId": "68656172742d646973656173652d6576616c"
"sessionKeyIv": "88a301385631ee67a2924ea1",
etc.

It is a small thing, but easy to fix.

**Comment by manju956** [comment]
There are few hex string values with '0x' prefix  like workOrderId, requesterId. the TCF core hex string utilities, Intel SGX related hex strings don't have the prefix. 
So, it would be appropriate to remove the prefix "0x" from the hex values with the prefix than modifying in many parts of framework code to add the prefix. 
Hopefully this approach is fine.

**Comment by kubasiemion** [comment]
This seems to have been qietly resolved...
:-D
