### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by jopasserat** [hyperledger/avalon#151]
Following the instructions in the [BUILD.md](avalon/BUILD.md) file for a Docker build in simulation mode fail silently:
the `docker-compose` finishes with `BUILD SUCCESS` but when entering the container to run the tests, the work folder doesn't contain the expected virtual environment:

```
ubuntu@ip-XX-XX-XX-XX:~$ docker exec -it tcf bash
root@193258dac9df:/project/TrustedComputeFramework/tools/build# source _dev/bin/activate
bash: _dev/bin/activate: No such file or directory
root@193258dac9df:/project/TrustedComputeFramework/tools/build# ls
Makefile  _dev
root@193258dac9df:/project/TrustedComputeFramework/tools/build# ls _dev/
opt
```

This was introduced after commit 6eea60eef5cc5a943ef1c72ea6b3878e4979237c since I could run the whole procedure successfully at that point in time.

Reproduced on several AWS EC2 instances (t2.XX) on Ubuntu 18.04 by @bertmiller and myself.

**Comment by jopasserat** [comment]
Could this be related to this issue? https://lists.hyperledger.org/g/avalon/topic/tcf_avalon_build_broken/36490392?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,36490392

And was this PR meant to solve this as well? https://github.com/hyperledger-labs/trusted-compute-framework/pull/144

**Comment by danintel** [comment]
@jopasserat I think they  are separate because #144 results in build errors (but the `_dev/bin/activate` script is created OK). While the error here, #151, the `_dev/bin/activate` script is not built--so the build cannot start.

**Comment by manju956** [comment]
> Following the instructions in the [BUILD.md](avalon/BUILD.md) file for a Docker build in simulation mode fail silently:
> the `docker-compose` finishes with `BUILD SUCCESS` but when entering the container to run the tests, the work folder doesn't contain the expected virtual environment:
> 
> ```
> ubuntu@ip-XX-XX-XX-XX:~$ docker exec -it tcf bash
> root@193258dac9df:/project/TrustedComputeFramework/tools/build# source _dev/bin/activate
> bash: _dev/bin/activate: No such file or directory
> root@193258dac9df:/project/TrustedComputeFramework/tools/build# ls
> Makefile  _dev
> root@193258dac9df:/project/TrustedComputeFramework/tools/build# ls _dev/
> opt
> ```
> 
> This was introduced after commit [6eea60e](https://github.com/hyperledger/avalon/commit/6eea60eef5cc5a943ef1c72ea6b3878e4979237c) since I could run the whole procedure successfully at that point in time.
> 
> Reproduced on several AWS EC2 instances (t2.XX) on Ubuntu 18.04 by @bertmiller and myself.

@jopasserat Virtual environment is removed in the docker based environment. Hence, there is no need to activate the virtual environment before executing test cases. 
Documentation was not updated to reflect this change. Following PR has been already raised to remove virtual environment references in docker.
https://github.com/hyperledger/avalon/pull/142/

**Comment by jopasserat** [comment]
ok i see, but how will this comply with this comment https://github.com/hyperledger/avalon/pull/142#issuecomment-544607904 which i think is very sensible

**Comment by danintel** [comment]
I do not see how you can comply with that comment, as Docker and non-Docker installation will always differ. But minimizing the differences is always good, when possible.
