### ISSUE TITLE
Problems initiating avalon

### ISSUE THREAD

**Issue by pegartillo95** [hyperledger/avalon#410]
We have an azure machine running Ubuntu 18.04 and with the Confidential Computing turned on.
We have also followed all the steps from the prerequisites guide.
Now we are trying to build as Hardware Mode but inside docker.
We had the problem of having to change /dev/sgx by /dev/isgx and we have already fixed it.
After that we were missing the registration in IAS but now we have already been registered and we have both our SPID and our its_api_key correctly setted on the tcs_config.toml file.
And we are still getting the following error.
```
avalon-sgx-enclave-manager    | Initializing Avalon Intel SGX Enclave
avalon-sgx-enclave-manager    | 
avalon-sgx-enclave-manager    | Enclave path: /project/avalon/tc/sgx/trusted_worker_manager/enclave/build/lib/libtcf-enclave.signed.so
avalon-sgx-enclave-manager    | 
avalon-sgx-enclave-manager    | SPID: F8D5BD4E90E4121B34C2B2012BF9F3BF
avalon-sgx-enclave-manager    | 
avalon-lmdb                   | 2020-04-08 13:04:53,258 - INFO - Received a new request from the client
avalon-sgx-enclave-manager    | [13:04:54 ERROR   avalon_enclave_manager.enclave_manager] failed to initialize enclave; Failed to initialize quote in enclave constructor: SGX ERROR: SGX_ERROR_SERVICE_UNAVAILABLE
avalon-sgx-enclave-manager    | Traceback (most recent call last):
avalon-sgx-enclave-manager    |   File "/usr/local/lib/python3.6/dist-packages/avalon_enclave_manager/enclave_manager.py", line 447, in start_enclave_manager
avalon-sgx-enclave-manager    |     enclave_helper.initialize_enclave(config.get("EnclaveModule"))
avalon-sgx-enclave-manager    |   File "/usr/local/lib/python3.6/dist-packages/avalon_enclave_manager/avalon_enclave_helper.py", line 36, in initialize_enclave
avalon-sgx-enclave-manager    |     return avalon_enclave.initialize_with_configuration(enclave_config)
avalon-sgx-enclave-manager    |   File "/usr/local/lib/python3.6/dist-packages/avalon_enclave_manager/avalon_enclave_bridge.py", line 135, in initialize_with_configuration
```

Are we doing anything wrong?

**Comment by manju956** [comment]
> SGX_ERROR_SERVICE_UNAVAILABLE

From the error, it appears to be an issue with aesm service that runs on host. Could you please confirm if aesmd service is running (sudo service aesmd status) ?

**Comment by pegartillo95** [comment]
This is the output I get by running the command you say.
```
dcapuser@DCAP01:~/avalon$ sudo service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-04-08 09:40:59 UTC; 4 days ago
 Main PID: 1763 (aesm_service)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/aesmd.service
           └─1763 /opt/intel/sgx-aesm-service/aesm/aesm_service

Apr 08 09:40:57 DCAP01 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Apr 08 09:40:59 DCAP01 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Apr 08 09:41:00 DCAP01 aesm_service[1763]: The server sock is 0x1ac62b0
```
It seems like is running, or am I wrong?

**Comment by manju956** [comment]
From the service logs, it looks like DCAP based aesm is running. Currently Avalon doesn't support DCAP. So, its recommended to uninstall all DCAP based SGX binaries like libsgx-enclave-common, sgx-driver and install all isgx based binaries. this is also captured in documentation as part of PREREQUISITES.md

**Comment by pegartillo95** [comment]
Why do you say the DCAP based aesm is running?
Because the name DCAP01 is the one from our machine just because we used it previously to test the DCAP feature but now we are trying to run the Avalon with the IAS service instead of the DCAP.

**Comment by pegartillo95** [comment]
P.D. Maybe the logs say we are running DCAP based aesmd but I can't see where sorry.

**Comment by manju956** [comment]
> P.D. Maybe the logs say we are running DCAP based aesmd but I can't see where sorry.

Since you mentioned you were running DCAP before, all the binaries installed on the host is of the type DCAP. Though, we install isgx based binaries in docker, it doesn't help because they need to interact with hardware using driver. So, suggest you remove all the binaries on the host machine and install isgx based binaries prescribed in documentation.

**Comment by danintel** [comment]
DCAP is not supported and needs to be uninstalled.  Install the isgx driver instead.  See
https://github.com/hyperledger/avalon/blob/master/PREREQUISITES.md#sgx

**Comment by pankajgoyal2** [comment]
@pegartillo95 Did you try to uninstall DCAP based SGX binaries and install isgx driver instead? is it working now? Please update the status here.

**Comment by pegartillo95** [comment]
Sorry because I opened this issue and forgot completely about it. Yes, now it is working and it had to be something related to the DCAP based SGX files because when erasing them and trying again the whole process it worked perfectly.
Sorry for nor answering before it was my bad.

**Comment by pankajgoyal2** [comment]
Thanks @pegartillo95 for replying. I am glad to hear that it is working for you now. Please raise any other concern, if you found anything. I'm going to close this issue now.
