### ISSUE TITLE
RSA encryption key size inconsistent (code/docs)

### ISSUE THREAD

**Issue by kubasiemion** [hyperledger/avalon#433]
This is in common/cpp/crypto:
In the README.md: 

> Asymmetric encryption | RSA-OAEP | 3072 | (1)

In the pkenc.h:

>  //***RSA is not quantum resistant ***//
> //*** USE 3072 for long term security ***//
> const int RSA_KEY_SIZE = 2048;

I understand this is a transition-issue, but still confusing...

**Comment by danintel** [comment]
Yes, this needs to be updated to RSA-3072.

**Comment by danintel** [comment]
Not a bug.
Withdrawing this PR. The code is correct.  The 2048 byte buffer allows up to RSA-16384 (2048*8) bits.
I added a comment with PR #443 to avoid future confusion.
