### ISSUE TITLE
OpenSSL - libssl1.1_1.1.1d-2_amd64.deb file not found

### ISSUE THREAD

**Issue by velu2020** [hyperledger/avalon#474]
Hi,

In your required package section, mentioned downloading the OpenSSL libssl1.1_1.1.1d-2_amd64.deb, that particular version is not found in http://http.us.debian.org/debian/pool/main/o/openssl/.  Can we use the latest version libssl1.1_1.1.1g-1_amd64.deb. Will it work with the current hyper ledger avalon model. Thanks.

Regards,
Velu - Intel

**Comment by danintel** [comment]
The updated instructions are here in PR #476 :

https://github.com/hyperledger/avalon/pull/476/files

The OpenSSL package download link constantly changes and must be changed every few months.

The corrected instructions will appear in the documentation once this PR is approved.

**Comment by pankajgoyal2** [comment]
@velu2020 The fix is available in master branch now. Please confirm if your issue is resolved. So that I can close this issue.

**Comment by danintel** [comment]
PR #476, which fixes this issue, is not integrated, so I am closing this.
