### ISSUE TITLE
SGX Hardware mode build error: get_signature_revocation_lists HTTP Error code : 401

### ISSUE THREAD

**Issue by justalittlenoob** [hyperledger/avalon#519]
I am trying to execute a Docker-based build and execution. 
1. SGX driver(`/dev/isgx`) is installed and can work. Did i miss something?   
2. Do i need to add environment variables TCF_ENCLAVE_CODE_SIGN_PEM and TCF_HOME on the host machine? (because it is a docker-based build, i think it is not a must)   

Any advice would be appreciated. Thanks in advance.

`sudo docker-compose -f docker-compose.yaml -f docker-compose-sgx.yaml up --build`

avalon-enclave-manager        | [17:19:26 INFO    avalon_enclave_manager.enclave_manager] Received empty list of work orders from wo-scheduled table
avalon-enclave-manager        | [17:19:26 INFO    avalon_enclave_manager.enclave_manager] Enclave manager sleeping for 10 secs
avalon-sgx-enclave-manager    | [17:19:33 INFO    avalon_enclave_manager.avalon_enclave_bridge] EPID: 00000B42
avalon-sgx-enclave-manager    | [17:19:34 WARNING STDERR] /usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
avalon-sgx-enclave-manager    | [17:19:34 WARNING STDERR]   InsecureRequestWarning)
**avalon-sgx-enclave-manager    | [17:19:34 ERROR   avalon_enclave_manager.ias_client] get_signature_revocation_lists HTTP Error code : 401**
avalon-sgx-enclave-manager    | [17:19:34 WARNING **avalon_enclave_manager.avalon_enclave_bridge] Failed to retrieve initial sig rl from IAS: 401 Client Error: Access Denied for url: https://api.trustedservices.intel.com/sgx/dev/attestation/v3/sigrl/00000B42**
avalon-sgx-enclave-manager    | [17:19:34 WARNING avalon_enclave_manager.avalon_enclave_bridge] Retrying in 60 sec

**Comment by pankajgoyal2** [comment]
@justalittlenoob Can you check the following:
1. aesm service is up and running on host machine
2. You obtained Intel IAS subscription key and SPID (as descirbed in [here)](https://github.com/hyperledger/avalon/blob/master/BUILD.md#standalone-installing-avalon-using-scripts) and follow step 5. This is applicable in docker mode also.
3. You no need to set TCF_ENCLAVE_CODE_SIGN_PEM and TCF_HOME in docker build mode.

Let me know if you still get the issues.

**Comment by justalittlenoob** [comment]
@pankajgoyal2   
Hi, thank you very much for your advice, it's very helpful. The root cause is I didn't configure subscription and SPID. Now it works.
