### ISSUE TITLE
Redundant code assigning WorkerId

### ISSUE THREAD

**Issue by MarkYQJ** [hyperledger/avalon#706]
```
worker_id = input_value_json["params"]["workerId"]
```
are redundant at

https://github.com/hyperledger/avalon/blob/b0ef7271c48282518470607269a0e5b277f015cf/listener/avalon_listener/tcs_work_order_handler_sync.py#L93
and
https://github.com/hyperledger/avalon/blob/b0ef7271c48282518470607269a0e5b277f015cf/listener/avalon_listener/tcs_work_order_handler_sync.py#L95

**Comment by manju956** [comment]
raised https://github.com/hyperledger/avalon/pull/734 to fix the issue, closing this issue.
