### ISSUE TITLE
name 'signup_cpp_obj' is not defined

### ISSUE THREAD

**Issue by zhaixuepan** [hyperledger/avalon#737]
`sudo docker-compose -f docker-compose.yaml -f docker/compose/avalon-pool.yaml up --build`

docker-compose build successful，docker-compose up failed

The error log is as follows：
avalon-wpe                | [03:34:07 ERROR   avalon_enclave_manager.base_enclave_manager] failed to initialize/signup enclave; name 'signup_cpp_obj' is not defined
avalon-wpe                | Traceback (most recent call last):
avalon-wpe                |   File "/usr/local/lib/python3.6/dist-packages/avalon_enclave_manager/base_enclave_manager.py", line 142, in _setup_enclave
avalon-wpe                |     signup_data = self._create_signup_data()
avalon-wpe                |   File "/usr/local/lib/python3.6/dist-packages/avalon_enclave_manager/wpe/wpe_enclave_manager.py", line 64, in _create_signup_data
avalon-wpe                |     verification_key_nonce = signup_cpp_obj.GenerateNonce(32)
avalon-wpe                | NameError: name 'signup_cpp_obj' is not defined

Source Code：enclave_manager\avalon_enclave_manager\wpe\wpe_enclave_manager.py，Line 64
```
# Generate a nonce in trusted code
verification_key_nonce = signup_cpp_obj.GenerateNonce(32)
```

**Comment by rranjan3** [comment]
Closing for merged fix #743 .
