### ISSUE TITLE
problem when running 'sudo docker-compose -f docker-compose.yaml -f docker-compose-sgx.yaml up --build'

### ISSUE THREAD

**Issue by kunmel** [hyperledger/avalon#747]
I got the following  error when running 'sudo docker-compose -f docker-compose.yaml -f docker-compose-sgx.yaml up --build' when it build avalon-enclave-manager at step 16/85:
`
/bin/sh: 1: wget: not found
ERROR: Service 'avalon-enclave-manager' failed to build : The command '/bin/sh -c OPENSSL_VER=1.1.1g  && wget https://www.openssl.org/source/openssl-$OPENSSL_VER.tar.gz  && tar -zxf openssl-$OPENSSL_VER.tar.gz  && cd openssl-$OPENSSL_VER/  && ./config  && THREADS=8  && make -j$THREADS  && make test  && make install -j$THREADS' returned a non-zero code: 127
`
But i dont know what's the problem. I'm new in avalon and blockchain. Can anyone help me? Thanks a lot.

**Comment by pankajgoyal2** [comment]
from the logs, it looks like it failed because "wget" is not installed. But it is strange. "wget" should get installed in Dockerfile. Can you check if it was the case?

**Comment by kunmel** [comment]
> from the logs, it looks like it failed because "wget" is not installed. But it is strange. "wget" should get installed in Dockerfile. Can you check if it was the case?

Thanks a lot. I noticed that the Dockerfile in mater branch and pre-release-v0.6 are different,  the Dockerfile in pre-release-v0.6 has `RUN  apt-get install wget ` but the Docerfile in master branch dont.
so i tried to run it again  on pre-release-v0.6.It works now, but i dont know if it is the reason?

**Comment by pankajgoyal2** [comment]
> > from the logs, it looks like it failed because "wget" is not installed. But it is strange. "wget" should get installed in Dockerfile. Can you check if it was the case?
> 
> Thanks a lot. I noticed that the Dockerfile in mater branch and pre-release-v0.6 are different, the Dockerfile in pre-release-v0.6 has `RUN apt-get install wget ` but the Docerfile in master branch dont.
> so i tried to run it again on pre-release-v0.6.It works now, but i dont know if it is the reason?

You can refer Dockerfile in master branch at https://github.com/hyperledger/avalon/blob/master/enclave_manager/Dockerfile#L73

**Comment by kunmel** [comment]
> > > from the logs, it looks like it failed because "wget" is not installed. But it is strange. "wget" should get installed in Dockerfile. Can you check if it was the case?
> > 
> > 
> > Thanks a lot. I noticed that the Dockerfile in mater branch and pre-release-v0.6 are different, the Dockerfile in pre-release-v0.6 has `RUN apt-get install wget ` but the Docerfile in master branch dont.
> > so i tried to run it again on pre-release-v0.6.It works now, but i dont know if it is the reason?
> 
> You can refer Dockerfile in master branch at https://github.com/hyperledger/avalon/blob/master/enclave_manager/Dockerfile#L73

Thank you very much for your advice, it's very helpful! I tried it again in master branch, and it works now.
