### ISSUE TITLE
Which document to read about proxy model with fabric?

### ISSUE THREAD

**Issue by kunmel** [hyperledger/avalon#757]
I am a beginner in avalon. I noticed avalon can connect with fabric in proxy model and i want to know their detailed interaction flow, and how can i get start. Please tell me which documents should I read ?
Thanks a lot!!!!

**Comment by rranjan3** [comment]
https://github.com/hyperledger/avalon/blob/master/docs/TestingFabricProxyModel.rst - Refer this to get started with trying out the Fabric proxy model.

**Comment by kunmel** [comment]
> https://github.com/hyperledger/avalon/blob/master/docs/TestingFabricProxyModel.rst - Refer this to get started with trying out the Fabric proxy model.

Thanks a lot for your help！

**Comment by kkkkkkkkkkkkkkkk123** [comment]
@rranjan3 
Hello, I'm following the https://github.com/hyperledger/avalon/blob/master/docs/TestingFabricProxyModel.rst , but i meet an error when i try to run ```./generic_client.py -b fabric --workload_id "echo-result" --in_data "Hello" -o --worker_id "singleton-worker-1"``` in avalon-shell container. Could you please check   #758  and give me some help?
